### PR TITLE
Fixed Sonar critical and major violations:

### PR DESCRIPTION
**Pull request by damianszczepanik**
- "static final" arrays should be "private"
- "for" loop incrementers should modify the variable being tested in the loop's stop condition
- Declarations should use Java collection interfaces such as "List" rather than specific implementation classes such as "LinkedList"

Pull #319

### CODE REVIEW

**Comment by romani** [comment]
thanks a lot !

**Comment by romani** [comment]
@damianszczepanik , please keep message of commit compact , all details you can put to PR or issue , please read http://checkstyle.sourceforge.net/contributing.html#Submitting_your_contribution on how to make ideal for us commit message

**Comment by damianszczepanik** [comment]
Looks like Sonar did not pull new sources to update report.

**Comment by romani** [comment]
lets wait for few days, looks like validation triggered not by git changes but as strict period time. If nothing happen we could ping sonar team in mail-list to clarify a period of refresh.

**Pull request merged**
