### PR TITLE
Collection with imports shall be cleared after visiting tree.

### PR DESCRIPTION
**Pull request by damianszczepanik**
I copied piece of code from this class and found that if list with imports is not cleared after visiting tree than invalid (additional) errors may be reported. It happened to me when I run checkstyle for project that has ~30k lines.

### CODE REVIEW

**Comment by romani** [comment]
It will be better to do it in beginTree method
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/api/Check.java#L144

as if any exception during validation happen , collections will not be cleared.

**Comment by romani** [comment]
@damianszczepanik, please review your PR, it has 3 commits, and not all changes are yours, please do rebase from our master.

**Comment by romani** [comment]
please also make sure that commit message always reference to github issue/pr in message, see other commits for example.

**Comment by damianszczepanik** [comment]
I will send this PR again.

**Pull request closed without merging**
