### PR TITLE
Issue #550: added dynamic checkstyle regression

### PR DESCRIPTION
**Pull request by rnveach**
Issue #550

Idea is:
New test will scan checkstyle's sevntu config and add missing checks on the fly, especially new ones from PR.
Will run checkstyle on checkstyle project and expect no violations.

Future enhancements could include ability to specify non-default configuration of checks.
Could be made as a groovy script, but will have to be able to tell what checks are available.

### CODE REVIEW

**Comment by rnveach** [comment]
````
Running com.github.sevntu.checkstyle.internal.CheckstyleRegressionTest
Working Path: /home/travis/build/sevntu-checkstyle/sevntu.checkstyle
Config Path: /home/travis/build/sevntu-checkstyle/sevntu.checkstyle/checkstyle/config/checkstyle_sevntu_checks.xml
Suppression Path: /home/travis/build/sevntu-checkstyle/sevntu.checkstyle
Found module not in sevntu: SuppressionFilter
Found module not in sevntu: FileContentsHolder
Found module not in sevntu: SuppressWithNearbyCommentFilter
Adding 4 missing check(s)
-- Adding com.github.sevntu.checkstyle.checks.coding.ReturnCountExtendedCheck
-- Adding com.github.sevntu.checkstyle.checks.design.ConstructorWithoutParamsCheck
-- Adding com.github.sevntu.checkstyle.checks.coding.AvoidModifiersForTypesCheck
-- Adding com.github.sevntu.checkstyle.checks.design.HideUtilityClassConstructorCheck
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.856 sec - in com.github.sevntu.checkstyle.internal.CheckstyleRegressionTest
````

Test passed as expected.

````
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (sevntu-checkstyle-check) on project checkstyle: Failed during checkstyle configuration: Exception was thrown while processing /home/travis/build/sevntu-checkstyle/sevntu.checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java: NullPointerException -> [Help 1]
````

NPE in regression is not expected.

**Comment by rnveach** [comment]
First Exception:
````
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /home/travis/build/sevntu-checkstyle/sevntu.checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.java
Caused by: java.lang.NullPointerException
	at com.github.sevntu.checkstyle.checks.design.ConstructorWithoutParamsCheck.visitToken(ConstructorWithoutParamsCheck.java:153)
````

**Comment by rnveach** [comment]
Regression is complete. No more exceptions.
Instead we have violations from check that were randomly added:
````
[INFO] --- maven-checkstyle-plugin:2.17:check (sevntu-checkstyle-check) @ checkstyle ---
[INFO] There are 3 errors reported by Checkstyle 7.3 with /home/travis/build/sevntu-checkstyle/sevntu.checkstyle/checkstyle/config/checkstyle_sevntu_checks.xml ruleset.
[ERROR] src/main/java/com/puppycrawl/tools/checkstyle/checks/ClassResolver.java:[73,21] (extension) ReturnCountExtended: Return count for 'resolve' method is 5 (max allowed is 1).
[ERROR] src/main/java/com/puppycrawl/tools/checkstyle/utils/AnnotationUtility.java:[139,29] (extension) ReturnCountExtended: Return count for 'getAnnotation' method is 2 (max allowed is 1).
[ERROR] src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java:[110,28] (extension) ReturnCountExtended: Return count for 'isCommentConsistent' method is 3 (max allowed is 1).
````
Will add code to provide suppression for this Check.

**Comment by rnveach** [comment]
@romani This is ready to go.

**Comment by romani** [comment]
missed Checks should be activated in main repo.
Please activate them and suppress to resolve step by step.
Please make this UT fail is smth is missed.

**Comment by rnveach** [comment]
> Please make this UT fail if smth is missed.

@romani This UT can not be set to fail if a check is missing. This is the whole reason we took this path.
If new check is in PR, CI will fail that check is missing from checkstyle. But checkstyle can't add new check until sevntu releases it which is after the PR.

The best thing we can do is make UT in checkstyle repo requiring all sevntu checks.

**Comment by romani** [comment]
we could grab all Check list from http://sevntu-checkstyle.github.io/sevntu.checkstyle/apidocs/allclasses-frame.html
it could be done by shell commands even.

**Pull request merged**
