### PR TITLE
Issue #417: Rename checks to follow Checkstyle convention for check names

### PR DESCRIPTION
**Pull request by MEZk**

### CODE REVIEW

**Comment by romani** [comment]
such names should be all around configuration files, not only in code.

**Comment by MEZk** [comment]
@romani 
Why we should use the whole name in xml? In main project we use names without ```Check```.

**Comment by romani** [comment]
I do not remember, but there are bunch of configs for different tools, some of them use their own way of Check loadings from class path.

**Comment by MEZk** [comment]
@romani 
Corrected.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
