### PR TITLE
config: bump checkstyle version to 8.37 (same as elipse-cs version)

### PR DESCRIPTION
**Pull request by romani**

### CODE REVIEW

**Comment by rnveach** [comment]
@romani Shouldn't all versions be kept in synch?

https://github.com/sevntu-checkstyle/sevntu.checkstyle/search?l=Maven+POM&q=%228.29%22

**Comment by romani** [comment]
Not all, some depends on eclipse cs , others are maven build run time

**Comment by rnveach** [comment]
@romani But then how can sonar work when it is using an old version and actual sevntu and others is using a newer version? What about breaking changes between the 2?

**Comment by romani** [comment]
Eclipse extension is always behind.
All extensions are independent, unfortunately bond by same version of project

**Pull request merged**
