### PR TITLE
config: bump multiple versions

### PR DESCRIPTION
**Pull request by rnveach**
updated eclipse-cs, junit, and powermock

### CODE REVIEW

**Comment by rnveach** [comment]
Even though cobertura passed, it printed lots of warnings.
https://travis-ci.org/sevntu-checkstyle/sevntu.checkstyle/builds/176582451#L787
Looks like it was because of the move to Java 8.
http://stackoverflow.com/a/25382674/1016482

**Comment by romani** [comment]
why StaticMethodCandidateCheckTest.java  is changed ?

**Comment by rnveach** [comment]
I'll fix the formatting for the file. It was changed because it uses `import org.apache.commons.lang3.ArrayUtils;` and we removed that from the latest CS code, so it was getting a compile error.

I currently can't figure out why code coverage is saying everything is 0 on a version upgrade.

**Comment by romani** [comment]
Look how upgrade to java8 was done in checkstyle, there were some changes for cobertura

**Comment by rnveach** [comment]
If this passes and no more changes are requested it can be merged, I will try to work on upgrading cobertura to remove warnings.

**Pull request merged**
