### PR TITLE
minor: dos2unix

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by rnveach** [comment]
@vorburger Have you tried setting `core.eol` to force files to dos crlf?
https://git-scm.com/docs/git-config

**Comment by vorburger** [comment]
@rnveach no, I wouldn't want to - you guys have mixed EOL in this repo, which is bad. You need to decide if you want *NIX or Windows EOL, and then have it uniform. IMHO it is now widely accepted that *NIX EOL in the repo is the way to go, and most repos I see do this - even if you let Windows users locally have Win EOL through Git's auto conversion (although it's perfectly possible to just simplify and use *NIX on Win as well).

The point of this Pull Request is to propose making a few of the files in this repo which have Windows EOL to have *NIX EOL - like all other files in this repo.

**Comment by rnveach** [comment]
> is to propose making a few of the files in this repo which have Windows EOL to have *NIX EOL

Sorry, I was under the impression the whole repo was dos. I wasn't having any issues with `autocrlf` off and I think I had some type of problem when initially trying it on, so I just assumed.

Doing a search of `*.java *.xml *.pom *.properties` the results were:
`[^\r]\n` gave 355 files.
`\r\n` gave 14 files, listed below.
````
eclipsecs-sevntu-plugin\src\com\github\sevntu\checkstyle\checks\annotation\checkstyle-metadata.properties
eclipsecs-sevntu-plugin\src\com\github\sevntu\checkstyle\checks\annotation\checkstyle-metadata.xml
eclipsecs-sevntu-plugin\src\com\github\sevntu\checkstyle\checks\naming\checkstyle-metadata.xml
eclipsecs-sevntu-plugin\src\com\github\sevntu\checkstyle\checks\sizes\checkstyle-metadata.properties
eclipsecs-sevntu-plugin\src\com\github\sevntu\checkstyle\checks\sizes\checkstyle-metadata.xml
sevntu-checks\src\main\java\com\github\sevntu\checkstyle\checks\annotation\ForbidAnnotationElementValueCheck.java
sevntu-checks\src\test\java\com\github\sevntu\checkstyle\checks\annotation\ForbidAnnotationElementValueCheckTest.java
sevntu-checks\src\test\java\com\github\sevntu\checkstyle\internal\ChecksTest.java
sevntu-checks\src\test\java\com\github\sevntu\checkstyle\internal\CheckUtil.java
sevntu-checks\src\test\java\com\github\sevntu\checkstyle\internal\XmlUtil.java
sevntu-checks\src\test\resources\com\github\sevntu\checkstyle\checks\annotation\ForbidAnnotationElementValueCheck2Input.java
sevntu-checks\src\test\resources\com\github\sevntu\checkstyle\checks\annotation\ForbidAnnotationElementValueCheckInput.java
sevntu-checks\src\test\resources\com\github\sevntu\checkstyle\checks\naming\InputAbstractClassName.java
sevntu-checkstyle-sonar-plugin\src\main\resources\com\github\sevntu\checkstyle\sonar\checkstyle-extensions.xml
````

So the majority does look like it is unix.

**Comment by vorburger** [comment]
This Pull Request fixes up 12 of the 14 you found (no idea why I missed 2). Again, as I said, this is a one-off manual, and it would be better if we could automate this to prevent it from happening again.

**Comment by rnveach** [comment]
@vorburger These are the 2 files missing from your list:
````
eclipsecs-sevntu-plugin\src\com\github\sevntu\checkstyle\checks\naming\checkstyle-metadata.xml
sevntu-checks\src\test\resources\com\github\sevntu\checkstyle\checks\naming\InputAbstractClassName.java
````

They could have been missed because they are mixed with `\n` and `\r\n`.
Please confirm they are wrong, fix them and I think this PR will be ready.

**Comment by vorburger** [comment]
@rnveach done (yeah I missed those that are mixed)

**Comment by romani** [comment]
yes, it is better to uniform all files to Unix. As all be in one format, git will do its job for auto-conversion.

**Pull request merged**
