### PR TITLE
Issue #915: convert maven-checkstyle-plugin to ant

### PR DESCRIPTION
**Pull request by rnveach**
Issue #915

### CODE REVIEW

**Comment by rnveach** [comment]
Output:
https://app.travis-ci.com/github/sevntu-checkstyle/sevntu.checkstyle/jobs/586409021#L859-L871

**Comment by romani** [comment]
>sevntu-checks/output.txt

Is not required.

We need to test that it reports violations by extra commit.

**Comment by rnveach** [comment]
> sevntu-checks/output.txt

Removed.

> We need to test that it reports violations by extra commit.

Done.

**Comment by rnveach** [comment]
Failure at https://app.travis-ci.com/github/sevntu-checkstyle/sevntu.checkstyle/jobs/586410408#L873

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by rnveach** [comment]
Just to note, travis still thinks removing only extra commits is a no-change to it. It failed with removing the extra commit until I did a no-change amend of the previous comment.

**Pull request merged**
