### PR TITLE
minor: update checks (related to checkstyle#3095)

### PR DESCRIPTION
**Pull request by nmancus1**
Related to https://github.com/checkstyle/checkstyle/pull/10574.

Regressions discovered in following reports:

https://nmancus1.github.io/issue-3095-b_check_diff_reports_2021_08_08/diff_sevntu-check-regression_part_1/index.html

https://nmancus1.github.io/issue-3095-b_check_diff_reports_2021_08_08/diff_sevntu-check-regression_part_2/index.html

Before merging this PR:

1. Checkstyle must release changes in https://github.com/checkstyle/checkstyle/pull/10574 (9.0)
2. The version of checkstyle in sevntu must update to the new eclipse-cs version 9.0

### CODE REVIEW

**Comment by kaushal-2002** [comment]
Hi, can I work on this?

**Comment by romani** [comment]
@kaushal-2002, please help with some other PR or issues, this PR is active and will be done this month.

**Comment by rnveach** [comment]
First post details why this PR is blocked.

**Comment by rnveach** [comment]
When this is merged, we must try to re-enable sevntu regression in checkstyle.

See https://github.com/checkstyle/checkstyle/issues/10778#issuecomment-913243531 and https://github.com/checkstyle/checkstyle/pull/10783.

**Review by romani — APPROVED** [review]
passing after rebase on master where we use 9.1

**Pull request merged**
