### PR TITLE
infra: complete migration to CircleCI

### PR DESCRIPTION
**Pull request by nrmancuso**
Completes migration of Travis jobs to CircleCI

### CODE REVIEW

**Comment by nrmancuso** [comment]
From https://app.circleci.com/pipelines/github/sevntu-checkstyle/sevntu.checkstyle/17/workflows/c5fa436e-b59c-44ea-b993-8e0d9d6d9dab/jobs/79?invite=true#step-103-544: `Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report (default-cli) on project sevntu-checks: Build error: Either repository token or service with job id must be defined`

@romani are you familiar with environment variables needed for coveralls?

**Comment by romani** [comment]
@rnveach , is this was introduced by you recently, I do not remember details.

**Comment by nrmancuso** [comment]
@romani @rnveach issue is created at https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/999, let's not block this PR.

**Review by romani — APPROVED** [review]
ok to merge

**Pull request merged**
