### PR TITLE
Fix for all javadoc problems in sevntu-checks project

### PR DESCRIPTION
**Pull request by daniilyar**

### CODE REVIEW

**Comment by romani** [comment]
failure is due to Checkstyle validation over the code :) - valid and need to be resolved.
https://travis-ci.org/sevntu-checkstyle/sevntu.checkstyle/jobs/122940982#L568

**Comment by daniilyar** [comment]
Ooops ) Where do I pick a proper Checkstyle config to see these violations in my Eclipse?

**Comment by romani** [comment]
it might not work in Eclipse, as we always use latest release, eclipse-cs is always behind
https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/pom.xml#L115

Please use maven command line, the same as travis:
https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/.travis.yml#L13

Please put a prefix in commit "Issue #XXXXX: ........" to make a link from commit to issue discussion. .... ok time to make it in sevntu project too - #451 is opened.

**Comment by daniilyar** [comment]
Done. 'mvn javadoc:javadoc' added to Travis build for sevntu-checks also

**Comment by romani** [comment]
merged !

thanks a lot !!!
we are in one step to publish that documents to our github.io to let users read docs n pretty view.

**Pull request merged**
