### PR TITLE
Issue 656: fix spelling of anon in DeclareAnonClassField

### PR DESCRIPTION
**Pull request by jsoref**
split from #655

### CODE REVIEW

**Comment by rnveach** [comment]
@jsoref Please fix commit message. It should be `Issue #{Number}: XXX`.

**Comment by romani** [comment]
Two CI failures:
- issue labels, will be fixed after we put approved label, we wait for description update.
- checkstyle-regression is expected, as we brake compatibility. Please send PR to checkstyle with changes, we will merge it after release of your fix. BTW , you can use such commit as example of what user should do to migrate.

**Comment by romani** [comment]
Please send PR to main repo and we are ok to merge

**Comment by romani** [comment]
@jsoref , please make comment like "Issue #656: CustomDeclarationOrderCheck: Correct spelling of DeclareAnonClassField".

and I am ok to merge.

**Pull request merged**
