### PR TITLE
Issue #672: added all condition operands to AvoidConstantAsFirst

### PR DESCRIPTION
**Pull request by rnveach**
Issue #672

### CODE REVIEW

**Comment by romani** [comment]
please update javadoc, just regression report to make sure no obvious exceptions happens and ok to merge.

**Comment by romani** [comment]
thanks a lot, just update javadoc to mention about not only "==".

**Comment by rnveach** [comment]
> update javadoc to mention about not only "==".

Done.

**Comment by romani** [comment]
travis falire:
{code}
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (attach-javadocs) on project sevntu-checks: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
[ERROR] /home/travis/build/sevntu-checkstyle/sevntu.checkstyle/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidConstantAsFirstOperandInConditionCheck.java:42: error: bad use of '>'
[ERROR]  * This check was extended to include all equality checks like ">", ">=", "<", "<=" for users who
[ERROR]                                                                 ^
[ERROR] /home/travis/build/sevntu-checkstyle/sevntu.checkstyle/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidConstantAsFirstOperandInConditionCheck.java:42: error: bad use of '>'
[ERROR]  * This check was extended to include all equality checks like ">", ">=", "<", "<=" for users who
[ERROR]                                                                      ^
[ERROR] /home/travis/build/sevntu-checkstyle/sevntu.checkstyle/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidConstantAsFirstOperandInConditionCheck.java:42: error: malformed HTML
[ERROR]  * This check was extended to include all equality checks like ">", ">=", "<", "<=" for users who
[ERROR]                                                                            ^
[ERROR] /home/travis/build/sevntu-checkstyle/sevntu.checkstyle/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/coding/AvoidConstantAsFirstOperandInConditionCheck.java:42: error: malformed HTML
[ERROR]  * This check was extended to include all equality checks like ">", ">=", "<", "<=" for users who
[ERROR]                                                                                 ^
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/java-8-oracle/jre/../bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/travis/build/sevntu-checkstyle/sevntu.checkstyle/sevntu-checks/target/apidocs' dir.
[ERROR] 
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (attach-javadocs) on project sevntu-checks: MavenReportException: Error while generating Javadoc: 
{code}

**Comment by rnveach** [comment]
> travis 

Done.

**Pull request merged**
