### PR TITLE
Added PrimitiveLiteralCaseCheck

### PR DESCRIPTION
**Pull request by pbaranchikov**
This is an extension of UpperEll check for all the other primitive constants: double and float. Adds the ability to forth either upper or lower case.

### CODE REVIEW

**Comment by romani** [comment]
sorry for delay ... I did not not miss your PR.

**Comment by romani** [comment]
PrimitiveLiteralsCaseCheck.java

1) > Copyright (C) 2001-2013  Oliver Burn

please fix that 

2) 
> public int[] getDefaultTokens()

please override also getRequiredTokens and getAcceptableTokens , in nearest future they will become abstract.

3)
> final String astString = ast.getText();

as you introduced that variable please use it in all ast.getText() places

4)
> public boolean isSpecifierWrong(char specifier)

Please name method in positive manner "isSpecifierCorrect(char specifier)"

5)
> public char getCorrectSprcifier(char specifier)

please fix typo

6)
> private final String msgKey;

I do not like that you put message from Check to Enum. Enum should be simple and should not care about Check nuances and reporting (be ready to live outside of Check and be ready to be used in other Check).
I need more time to investigate how new Option will affect http://checkstyle.sourceforge.net/property_types.html, and how Eclipse-cs will support new options in his UI. To decide on location of that enum: inside Check or outside.

7) 
please generate a HTML report by https://github.com/checkstyle/contribution/tree/master/checkstyle-tester for your new check over all project that are referenced in property file and share report on github.io for review , all instructions and examples are et README.md .

**Comment by pbaranchikov** [comment]
1-5 - fixed
6 - added a separate Enum - CharacterCase
7 Could not execute report, as it fail with 4 violations in guava:
```xml
<error line="117" column="30" severity="error" message="Should use lowercase &apos;f&apos;." source="com.github.sevntu.checkstyle.checks.misc.PrimitiveLiteralsCaseCheck"/>
<error line="118" column="30" severity="error" message="Should use lowercase &apos;f&apos;." source="com.github.sevntu.checkstyle.checks.misc.PrimitiveLiteralsCaseCheck"/>
<error line="119" column="31" severity="error" message="Should use lowercase &apos;d&apos;." source="com.github.sevntu.checkstyle.checks.misc.PrimitiveLiteralsCaseCheck"/>
<error line="120" column="31" severity="error" message="Should use lowercase &apos;d&apos;." source="com.github.sevntu.checkstyle.checks.misc.PrimitiveLiteralsCaseCheck"/>
```

**Comment by romani** [comment]
postponed till 1.14 to let me release 1.13.6

**Comment by romani** [comment]
Sorry for long delay in reply

1)
> processors.put(CharacterCase.UPPER, new CaseProcessor()

please move anonymous classes to inner classes

2)
> public char getCorrectSpecifier(char specifier)

Correct == > Adjusted

3)
> return new int[] { TokenTypes.NUM_DOUBLE,
                TokenTypes.NUM_FLOAT, TokenTypes.NUM_LONG };

please make it a single column - it is easier to read

4) 
> public int[] getAcceptableTokens()

please call this method in getDefaultTokens()

5)
> // FOr primitives, ending with digit - no specifiers should be applied.

no specifier - no validation 

6) 
> Preconditions.checkNotNull(processor,
                "Processor should be set for CharacterCase " + option);

we have lower case and upper case , what other case you expect ?

7)
> final boolean correctSpecifier = processor
                .isSpecifierCorrect(specifier);

What force you to wrap that code ? please make it single line (limit is 100)

8)
> public static interface CaseProcessor
boolean isSpecifierCorrect(char specifier);

Please name class in specific way or rename methods inside to be general.

**Comment by romani** [comment]
@pbaranchikov , can we finish this PR ?

**Comment by romani** [comment]
@pbaranchikov , do you plan to finish this PR ?

If you have no time, just let me know, I find another contributor to finish.

**Comment by pbaranchikov** [comment]
1-8 - done
Moved `CharachterCase` into `PrimitiveLiteralsCaseCheckTest` as an inner class, as ImportOrder configuration does not permit `PrimitiveLiteralsCaseCheckTest` class to refer to `com.github.sevntu.checkstyle` package

**Comment by romani** [comment]
@pbaranchikov ,

1)
> TODO: switch to SingleSelect, when check migratest to main project

TODO is not allowed, please create issue on this in checkstyle/checkstyle

2)
> sevntu-checks/checkstyle.properties

remove this changes from PR.

3)
> Check, performing checks for literal numeric type specifiers case. Numeric

Should be "Checks for literal numeric type specifiers case. Numeric"

example: http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/checks/blocks/package-summary.html

> float constants cat be represented in different ways:

cat ==> can

4)
Please add example of default configuration and simple code with violations and without.
Please add config example with changes property "requiredCase" and example of code.

5)
> private final Map<CharacterCase, CaseValidationProcessor> processors;

you do not need all processors during run time. keep only one and create it in setter of "requiredCase". Check instance is created ones, configured ones for whole launch.

6)
>          final String astString = ast.getText();
        final char specifier = astString.charAt(astString.length() - 1);

please make a static function from this

7)
> return;

please make one exit point from method - at the end of method

8)
> protected enum CharacterCase {

Why protected ? please make it private. Inheritance in Checks make only problems. 

9)
https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/List-of-files-that-need-to-be-updated-for-new-field-or-new-Check-implementation
please create one more PR for gh-pages branch

10)
please provide testing results for your check over all projects in checkstyle-tester (I do not believe you will have a huge amount of violations). Please define property explicitly in config as UPPER to test that setter works fine too.

**Comment by romani** [comment]
@pbaranchikov , lets finish this PR, in 2 month it will be a 1 year as it hanging :).

**Comment by romani** [comment]
@pbaranchikov , lets finish this PR , it is hanging too much.

**Comment by romani** [comment]
we lost connection to Author of this code, I am closing PR .... if author or any other person ready to continue, we can reopen PR or start it from scratch.

**Pull request closed without merging**
