### PR TITLE
Improved AvoidHidingCauseExceptionCheck code coverage

### PR DESCRIPTION
**Pull request by damianszczepanik**
Pull #323

### CODE REVIEW

**Comment by romani** [comment]
please explain changes there - https://github.com/damianszczepanik/sevntu.checkstyle/commit/c0ba9a8d01328cd6be458fe4383790623f4e74b8#diff-94e041d44ef80aa4ede16b3cdb727f17L234

**Comment by romani** [comment]
please remove TODO from code and add that comment to Input. 
I am ok with merge.

Simple rule: all TODO should be converted to issue or resolved. In all other cases it will be never resolved.

**Comment by damianszczepanik** [comment]
Resolved conflicts and updated PR

**Comment by romani** [comment]
I still see "TODO" in code, it is not ok, please recheck sources on your local and github.

**Comment by damianszczepanik** [comment]
My fault, some local problem with amend and I sent the same sources again :(

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
