### PR TITLE
infra: removes majority of validation from travis and switch to GH

### PR DESCRIPTION
**Pull request by rnveach**
Removes travis as it fails too much.

### CODE REVIEW

**Comment by rnveach** [comment]
https://github.com/sevntu-checkstyle/sevntu.checkstyle/actions/runs/4328888245/jobs/7559005360
> Run ./.ci/validation.sh sonarqube
SONAR_TOKEN is not set

@romani How can we fix this?

**Comment by rnveach** [comment]
> [run (eclipse-cs)](https://github.com/sevntu-checkstyle/sevntu.checkstyle/actions/runs/4328888245/jobs/7559004919#logs)
java.io.FileNotFoundException: https://raw.githubusercontent.com/checkstyle/checkstyle/checkstyle-10.8.0/config/checkstyle_checks.xml

> [run (sonar-plugin)](https://github.com/sevntu-checkstyle/sevntu.checkstyle/actions/runs/4328888245/jobs/7559005047#logs)
ResourceNotFoundException: Could not find resource 'https://raw.githubusercontent.com/checkstyle/checkstyle/checkstyle-10.8.0/config/checkstyle_checks.xml'.

> [run (checkstyle-regression)](https://github.com/sevntu-checkstyle/sevntu.checkstyle/actions/runs/4328888245/jobs/7559005236#logs)
IllegalStateException: Can't read config: /home/runner/work/sevntu.checkstyle/sevntu.checkstyle/sevntu-checks/../.ci-temp/checkstyle/config/checkstyle_sevntu_checks.xml

All seem blocked by https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/990#issuecomment-1454337832 .

**Comment by rnveach** [comment]
> [run (sevntu-checks)](https://github.com/sevntu-checkstyle/sevntu.checkstyle/actions/runs/4328888245/jobs/7559005123#logs)
CommitValidationTest.testCommitMessageHasProperStructure:189 Commit 3bace8653663caadfa481e797a5949d65871b823 message: "Merge 7f6451021ab39893feede91b0962095a3c408e01 into 1572f8c562482b7b75e9e8139686bfe386db3546\n" is invalid

Not sure is this is related to the commit depth or how we can fix this. @nrmancuso Do you have any ideas?

**Review by romani — APPROVED** [review]
Let's do it .

When CI is green.

**Comment by rnveach** [comment]
@romani Please see https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/994#issuecomment-1454342303

**Comment by romani** [comment]
I pushed fix for no-exception on checkstyle  https://github.com/checkstyle/contribution/commit/1eeef003464a29303d443bfc8031399dd8d3f3c0

**Pull request closed without merging**
