### PR TITLE
config: added ForbidCertainMethodCheck

### PR DESCRIPTION
**Pull request by rnveach**

### CODE REVIEW

**Comment by rnveach** [comment]
@romani you want me to merge it?

**Comment by rnveach** [comment]
@romani If you didn't realize, this merge is for gh-pages. There is no travis for it and so CI won't be green.

**Comment by romani** [comment]
Travis is instructed to validate only master branch
https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/.travis.yml#L8

failure on Travis:
```
0.16s$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-2.4.1@global/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
The command "rake" exited with 1.
```

so failed on travis side ...., not related to your changes.

**Comment by rnveach** [comment]
> Travis is instructed to validate only master branch
https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/.travis.yml#L8

@romani `.travis` file is on master branch, however `gh-pages` branch has no `.travis` file and it doesn't know to look at another branch.
So failure is correct to fail.
If you don't want a failure, we will have to create a `.travis` file on `gh-pages` branch.

**Comment by romani** [comment]
Looks like there is no other way .... let do this, Travis failure always unplesant and force me to review it.

**Pull request merged**
