### PR TITLE
Code coverage improvement

### PR DESCRIPTION
**Pull request by damianszczepanik**
Pull #331

### CODE REVIEW

**Comment by romani** [comment]
changes are ok, please do rebase to resolve conflicts.

**Comment by romani** [comment]
please do rebase, I have a problem with merge.

**Comment by damianszczepanik** [comment]
Does it look better now? I did not have any conflict with this rebase.

**Comment by damianszczepanik** [comment]
@romani  can we complete this PR ?

**Comment by romani** [comment]
sorry, I just lost this PR from tracking, thanks for pinging me, merged as FF.

thank you very much !

**Pull request closed without merging**
