### PR TITLE
Issue #187: new Check - NumericLiteralNeedUnderscoreCheck

### PR DESCRIPTION
**Pull request by cypai**
See topic at https://groups.google.com/forum/#!topic/sevntu-checkstyle/8xuSZZj8W98

### CODE REVIEW

**Comment by romani** [comment]
build failure is problem of master code, I will fix it.

**Comment by romani** [comment]
even after rebase your code have too much errors -136 :  https://travis-ci.org/sevntu-checkstyle/sevntu.checkstyle/jobs/89936659#L493

Please rebase your code on latest HEAD and fix all checkstyle violations.

**Comment by romani** [comment]
@cypai , do you have time to finish this PR , i am going to make release at this weekend?

**Comment by cypai** [comment]
eclipse throws errors when I follow https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/Java-code-Formater-and-Checkstyle-configuration-for-development

I get:
cannot initialize module SuppressionFilter - Cannot set property 'file' to 'suppressions.xml' in module SuppressionFilter

and

cannot initialize module TreeWalker - Property 'ignoreOverridden' in module ParameterName does not exist, please check the documentation

I've spent a couple hours trying to figure this out, I'll try again later

**Comment by romani** [comment]
there is a problem with such instruction, as eclipse-cs is not updating as for each checkstyle version.

so we have right now checkstyle:6.13 vs eclipse-cs:6:12 , so that is why you have problems with new options. 

I would recommend you to use command line execution of checkstyle - https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/pom.xml#L100

I will think how to change a wiki to make it up to date.

**Comment by romani** [comment]
I did update to pom.xml to let run validation from terminal as "mvn process-classes" , https://github.com/sevntu-checkstyle/sevntu.checkstyle/commit/a1c4e16d02707fccf8bfd35b1231ebc8d6a9cede

**Comment by romani** [comment]
@cypai , can you finish this PR on this weekend to let me release you

**Comment by romani** [comment]
@cypai , now we have new requirement - "All sevntu Checks have to be applied to checkstyle code" , please add your check to https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_sevntu_checks.xml , make sure it works, send PR to Checkstyle project with fixes. Chekcstyle CI will fail as your Chekc is not released, but it is ok. I will merge your PR after sevntu release.

**Comment by cypai** [comment]
I will try to get this done this week

**Comment by cypai** [comment]
Travis now passes
Checkstyle PR will be done... later, not over the holiday weekend

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
