### PR TITLE
Issue #451: reworked travis and added PR desc testing

### PR DESCRIPTION
**Pull request by rnveach**
Issue #451

### CODE REVIEW

**Comment by rnveach** [comment]
@romani What do you think of this travis rewrite?
[Before the build took 6 minutes.](https://travis-ci.org/sevntu-checkstyle/sevntu.checkstyle/builds/180978673) This build took 3 minutes.
The longest being eclipse-cs because of external downloads and sadly the other items need quick install of sevntu for further checking.

If it is all ok, I will squash and merge for #451 as this will include PR test.

**Comment by romani** [comment]
good !
please prepare for merge.

side note and probably as next step idea:
review https://github.com/checkstyle/sonar-checkstyle/blob/master/.travis.yml , split of travis stuff into two files will give user ability to launch easily build item on his side.

**Comment by rnveach** [comment]
@romani Squashed and renamed commit.

**Comment by romani** [comment]
one day we need to question why we do "javadoc:javadoc" as separate step.
"mvn clean install" should be be enough.

**Pull request merged**
