### PR TITLE
Code coverage improvements for ReturnCountExtendedCheck

### PR DESCRIPTION
**Pull request by damianszczepanik**

### CODE REVIEW

**Comment by romani** [comment]
please do rebase, beware I did update today to that Check coverage line to pass a build on my local, not sure why it was ok for Travis.

**Comment by damianszczepanik** [comment]
I wonder why there is no more information about code coverage posted as comment.

**Comment by romani** [comment]
> ```[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:2.2.0:jacoco (default-cli) on project sevntu-checks: Processing of input or output data failed: Report submission to Coveralls API failed with HTTP status 504: Gateway Time-out (Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
```

https://travis-ci.org/sevntu-checkstyle/sevntu.checkstyle/jobs/53837116#L1593

it might be problem in versioning of jacoco plugin,

**Comment by romani** [comment]
merged as FF, thanks a lot !!

**Pull request closed without merging**
