### PR TITLE
Issue #669: removed branchContains for complicated cases (part 1)

### PR DESCRIPTION
**Pull request by rnveach**
Issue #669

Regression to come.

### CODE REVIEW

**Comment by rnveach** [comment]
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/159/

Seems there are differences with AvoidConstantAsFirstOperandInConditionCheck and PublicReferenceToPrivateTypeCheck. I'll need to look into and fix these.

**Comment by romani** [comment]
ones regression is resolved - ok to merge.

**Comment by rnveach** [comment]
@romani 
For `AvoidConstantAsFirstOperandInCondition`, to me it looks like these new violations are valid.

http://rveach.no-ip.org/checkstyle/regression/reports/159/guava/index.html#A1
http://rveach.no-ip.org/checkstyle/regression/reports/159/guava/xref/guava/src/com/google/common/base/SmallCharMatcher.java.html#L62
> `return 1 == (1 & (filter >> c));`

1 should be on the right side as it is a constant. It seems the majority of the violations follow this pattern. I will verify them all after I check the other check.
You agree? If so, I'll split it into a new issue.

**Comment by rnveach** [comment]
Issues for `PublicReferenceToPrivateType` also look valid.
http://rveach.no-ip.org/checkstyle/regression/reports/159/openjdk10/index.html#A2
http://rveach.no-ip.org/checkstyle/regression/reports/159/openjdk10/xref/src/java.base/share/classes/java/lang/invoke/MethodType.java.html#L199 - violation
http://rveach.no-ip.org/checkstyle/regression/reports/159/openjdk10/xref/src/java.base/share/classes/java/lang/invoke/MethodType.java.html#L1266 - inner class
http://rveach.no-ip.org/checkstyle/regression/reports/159/openjdk10/xref/src/java.base/share/classes/java/lang/invoke/MethodType.java.html#L1330 - nested inner class that extends another class

It looks like `branchContains` was going too deep and went from inner class to secondary inner class to get extends. Most of check only looks for private modifiers and this field is package-private so it can escape the class. Since this check is all about not allowing escape outside itself, this seems valid violation.
Agree?

**Comment by rnveach** [comment]
I will add cases as new tests and confirm the rest of the violations.

**Comment by rnveach** [comment]
I added new tests. Confirm `PublicReferenceToPrivateType` and this can be merged.

**Comment by romani** [comment]
> won't we assume it is something we missed in review

most likely but regression report generation is recent practice, such Checks far before.

> http://rveach.no-ip.org
Agree ?

service is not available.

**Comment by rnveach** [comment]
Storm in my area so I turned it off for safety. It should be coming up now.

**Comment by romani** [comment]
> http://rveach.no-ip.org/checkstyle/regression/reports/159/openjdk10/index.html#A2 

valid violations, look like we can file issue against openjdk.
ok to merge.

**Pull request merged**
