### PR TITLE
Issue #374: New SingleBreakOrContinueCheck - only one break or continue statement should be…

### PR DESCRIPTION
**Pull request by yaziza**
… inside cycle body

Signed-off-by: Yasser Aziza <yasser.aziza@gmail.com>

### CODE REVIEW

**Comment by romani** [comment]
Thanks a lot for first contribution.

1)
> ForbidMultipleBreakOrContinueCheck

I think name SingleBreakOrContinueCheck is better.

2)
> getDefaultTokens() 

please reformat elements of array to be on alone on a line.

3)
>  ```private List<DetailAST> breakOrContinue = new ArrayList<>();```

please refactor this member to local variable. We do not need state in this Check. It should be "stateless" in terms of logic.

4)
> private void visitChildren(DetailAST node)

should return amount of breaks. And have only one "return" - single point of exit from methods.

5)
> private static final int DEFAULT_BREAK_OR_CONTINUE_COUNT = 1;

Default count ..... I do not see user change change this value. Please remove this constant. 1 is not a magic number if name of Check is "Single......".

6)
please make changes in other related to project files , see example at https://github.com/sevntu-checkstyle/sevntu.checkstyle/commit/0ebb67094362e2db9e927233aceb9e1133ed40db

7)
We need to test you Check on real sources. Please take a look at https://github.com/checkstyle/contribution/tree/master/checkstyle-tester it is half-automated to generate HTML report to review. Please uncomment projects in property file and run your Check against these projects. Report need to shared with me at issue for additional verification.

PS: to let us proceed quickly, please reply with text like "1) done 2) done .... 5) I do not agree..... 7) I need help ,....." such little bureaucracy are good there to never miss a point of code-review.

**Comment by romani** [comment]
@yaziza  , now we have new requirement - "All sevntu Checks have to be applied to checkstyle code" , please add your check to https://github.com/checkstyle/checkstyle/blob/master/config/checkstyle_sevntu_checks.xml , make sure it works on your local, send PR to Checkstyle project with fixes. Chekcstyle CI will fail as your Chekc is not released, but it is ok. I will merge your PR after sevntu release.

**Comment by yaziza** [comment]
1) done
2) done
3) done
4) done
5) done
6) done, but not sure if i missed something
7) in progress 
8) in progess

Many thanks for your feedback !

**Comment by yaziza** [comment]
Hi @romani, 

i tested the new check against the Checkstyle code and found 7 violations, most of them are switch statements inside a loop. I will fix my code to ignore switch statements, and fix the other violations and send a PR. 

Or should this check apply also to switch statements inside a loop ?

Cheers,
Yasser

**Comment by yaziza** [comment]
Example: https://github.com/checkstyle/checkstyle/blob/a707819ab73dded873917fd33e22d45d0e3e1860/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/VariableDeclarationUsageDistanceCheck.java#L329

**Comment by yaziza** [comment]
And what about nested loops like this: https://github.com/checkstyle/checkstyle/blob/eeec3dc1d23916462560403a27a4ae94260d61f3/src/main/java/com/puppycrawl/tools/checkstyle/checks/coding/InnerAssignmentCheck.java#L225

Should those kind of loops reported or not ?

**Comment by yaziza** [comment]
7) done, tested against CS, SevnTU CS, PMD, Guava and Findbugs

Report: http://yaziza.github.io/checkstyle.html

**Comment by romani** [comment]
1)
> `for (int i = 1; i <= 10; i++) // Noncompliant - 2 continue`

please rename "noncompliant" to "violation". We use this term.

2)
Please add your Check to https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/gh-pages/sevntu-checkstyle-default-configuration.xml .

3)
> TokenTypes.LITERAL_FOR, TokenTypes.LITERAL_WHILE, TokenTypes.LITERAL_DO, };

Please put each Token on its own line.

4)
> ```if (visitChildren(ast.getFirstChild()) > 1) {
...
     * Gets the number of "continue" and "break" statements inside a loop.
    private int visitChildren(DetailAST node) {
```

"visit" is not a verb that meaning returning a value. please rename the method. Code should be clear even without reading of javadoc.

5)
Please remove from report "checkstyle/src/it/resources" that files are weird as they are inputs for UTs.

6)
So we have bunch of violations in sevntu-checkstyle and checkstyle projects all of them have to be fixed before Check is merged. In other case we will mark this Check as experimental and it will never appear in main project.
As a prove of concept we usually send PR to other project to get a feed back .
We need to make this Check usable by community so additional logic or extra options might need to be implemented.
In checkstyle we have a rule to follow each Check to make sure that it is usable and reasonable on our own code first, before we deliver it to whole java  community - "eat your own food".
For now I do not see that refactoring will make code better, but I will look more attentively to propose how to change the Check.

7) We have bunch violations on checkstyle's projects and Sonar do have the same rule. Do we have the same violations in Sonar ? - http://nemo.sonarqube.org/overview?id=com.puppycrawl.tools%3Acheckstyle , http://nemo.sonarqube.org/overview?id=com.github.sevntu.checkstyle%3Asevntu-checks

**Comment by romani** [comment]
8) we need to ignore all nested loops and switch blocks. Rule should validate loop structure only with depth 0. Please update and regenerate report.

**Comment by yaziza** [comment]
1) done
2) done
3) done
4) done
5) done
8) done

**Comment by romani** [comment]
> 5) How can i exclude all this resources from when generating a new report ?

Format description:
https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-to-test-on.properties#L2

ready to use examples: https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/projects-to-test-on.properties#L36

**Comment by romani** [comment]
1) please send PRs with resolving future violations in sevntu and checkstyle projects. We need to eat our food to make sure it is eat-able :) . All violations have to be resolved in our projects.

2) please put in report another project, for example "guava" or "spring" or "hibernate" or ....... and lets do refactoring for few cases (up to 5 cases) and send PR to that projects for review and feedback. It is ok share with me changes before PR.

**Comment by yaziza** [comment]
1) CS violation resolved
Sevntu violation 6/7 resolved

i will do some further refactoring/more testing, fix all build issues and upload a final patch this week end

2) In progess, will share a link for review

**Comment by romani** [comment]
@yaziza , I do not understand a reason of updates in other Checks, looks like formatting please remove this from this PR. If that is real formatting problems please propose them in separate PR.

Travis-CI has to be green to merge PR.

**Comment by yaziza** [comment]
@romani : i thought we need to resolve all violation before merging this PR.

Should all SingleBreakOrContinueCheck violation fixed in a separate PR ?

**Comment by romani** [comment]
please do this as separate commit of his PR, to make it clear that why we do this.
but functional changes(new Check) and  formatting (even they are caused by new Check) should be separate.

**Comment by romani** [comment]
code is ok to merge, just waiting for resolving violations on our code at #423 .

**Comment by yaziza** [comment]
Thank you!
I have fixed some violations from Facebook presto project:

https://github.com/yaziza/presto/commit/5ad6acbb9edf31970114e3ff0d225e039a01571c

Feedback highly appreciated !

**Comment by romani** [comment]
> Feedback highly appreciated !

1) remove all changes at are not related single-break refactoring. In other case such PR will never be merged.

2) All your 2 cases are very simple and the same type, Please do optimization for 2 more complicated cases as you did in our projects.

3) Send PR to original project and lets see how authors will react on it.

**Comment by romani** [comment]
merged as FF

**Pull request closed without merging**
