### PR TITLE
minor: test missing method

### PR DESCRIPTION
**Pull request by rnveach**
Currently testing out missing method that needs to be included.

### CODE REVIEW

**Comment by rnveach** [comment]
Regression says no new violations. I will keep this open until I'm sure I didn't miss anything else.

**Comment by rnveach** [comment]
based on what I saw in https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/605 , I may need to expand the check to flag methods that aren't `@Test` but call `verify` with no try/catch.
These type of methods are hidden from regression's view.

**Comment by rnveach** [comment]
https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/main/java/com/github/sevntu/checkstyle/checks/design/CheckstyleTestMakeupCheck.java#L220
We should update check to make sure we can identify class being created by `create` method since that is what we will be pulling in to identify for regression.

**Comment by romani** [comment]
@rnveach , do you need this PR ?

**Comment by rnveach** [comment]
@romani I am currently using it as a reminder of things I need to do for the regression check and project.
I plan to come back to this soon. I am waiting on finalizing the check in the regression project before I finalize everything that needs to be updated in this check.

**Comment by romani** [comment]
@rnveach , is there any plans to come back to this PR ? It doesn't like reminder that it actually works.

**Comment by romani** [comment]
@rnveach , I am closing this PR, to keep list of PRs clean.

**Pull request closed without merging**
