### PR TITLE
Pull #905: adds checkstyle verification to eclipsecs-sevntu-plugin

### PR DESCRIPTION
**Pull request by rnveach**
https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/441

### CODE REVIEW

**Comment by rnveach** [comment]
New line at https://app.travis-ci.com/github/sevntu-checkstyle/sevntu.checkstyle/jobs/585735717#L1553 . No violations.

**Review by romani — APPROVED** [review]
Ok to merge after removal of test commit

**Comment by rnveach** [comment]
Expected violation is not happening, something is not working.

**Comment by rnveach** [comment]
> [DEBUG] Added 0 files to process.

We can't use maven plugin because of https://github.com/checkstyle/contribution/issues/273 . Maven doesn't support non-Java files really.

**Comment by rnveach** [comment]
@romani This is now resolved. Switching to non-maven for CS run pulled in the files in the project.

This is part of https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/441 .

**Review by romani — APPROVED** [review]
Ok to merge

**Pull request merged**
