### PR TITLE
Issue #661: ignore instanceof in LogicConditionNeedOptimizationCheck

### PR DESCRIPTION
**Pull request by rnveach**
Issue #661

Regression to come.

### CODE REVIEW

**Comment by romani** [comment]
@rnveach ,

few more test inputs:
```
if ((o instanceof String)) {} // OK
if ( o==null && (o instanceof String)) {} // OK
if ( (o instanceof String) && o==null ) {} //VIOLATION
if ( o==null && (o instanceof String) && o!=null) {} // VIOLATION
if ( o==null && ((o instanceof String) && o!=null)) {} // VIOLATION
if ( o==null && ((o instanceof String) || o!=null)) {} // OK
if ( o==null && (o!=null && (o instanceof String))) {} // OK
```

**Comment by rnveach** [comment]
> if ( o==null && ((o instanceof String) || o!=null)) {} // OK
if ( o==null && (o!=null && (o instanceof String))) {} // OK

This is wrong. First one should have a violation because `instanceof` is before a simple null check inside the `||` condition.
Second one is correct and shows how statement should be written.

**Comment by romani** [comment]
your corrections are confirmed, you are right.

Lets have a look at regression,

**Comment by rnveach** [comment]
Regression: http://rveach.no-ip.org/checkstyle/regression/reports/164/

http://rveach.no-ip.org/checkstyle/regression/reports/164/apacheapex/index.html#A5
> if (t instanceof TestControlTuple && ((TestControlTuple)t).data == this.data) {

This is a false positive. `instanceof` is needed first to insure type can be cast.

**Comment by romani** [comment]
Yes, `instanceof` allow to write some special code further in expression, we might need to skip all related casts to same type. This seriously complicate logic as you need to thoroughly analyse whole expression.

**Comment by rnveach** [comment]
The other option is to ignore the violation if the first has `instanceof` and the second has a type-cast.

We could check type being the same as cast, but there could be weird reasons they aren't the same.
The appropriate way would be to verify the variable between the 2 operands are the same with the type-cast check.

I will just add the type-cast check for now. If it is an issue later, we can look into it more.

**Comment by romani** [comment]
> The appropriate way would be to verify the variable between the 2 operands are the same, along with the type-cast check and the variable is in the type-cast.

this is good.
skip all(in expression branch) that is followed instanceof is also ok. 
Any other solution that does not produce false-positives is ok. 
False-negative is much better, as it never fail a build :)

**Comment by rnveach** [comment]
Updated Regression: http://rveach.no-ip.org/checkstyle/regression/reports/166/

**Comment by rnveach** [comment]
Thanks for reviewing. I went to bed as soon as the report was ready.

http://rveach.no-ip.org/checkstyle/regression/reports/166/openjdk10/index.html#A20
> 3138         if ((t instanceof ForkJoinWorkerThread) &&
3139             (p = (wt = (ForkJoinWorkerThread)t).pool) != null &&
3140             (w = wt.workQueue) != null) {

This is a false positive because `wt` is assigned in condition 2 and then used in condition 3.
AST sees conditions as `(cond1 && cond2) && cond3` instead of `cond1 && cond2 && cond3`. Since condition 1 has an `instanceof` and condition 3 doesn't have a typecast, it thinks it can swap the 2 in favor of `cond3 && (cond1 && cond2)`.

This seems like a general issue and not directly related to my changes.

````
$ cat TestClass.java
public class TestClass {
    private int field = 1;

    void method() {
TestClass s = new TestClass(), t = null, u = null;

        if (((t = s).test()) &&
            ((u = t).field == 1) != null &&
            (u.field) != 2) {}
    }

    public boolean test() { return true; }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="com.github.sevntu.checkstyle.checks.coding.LogicConditionNeedOptimizationCheck" />
    </module>
</module>

$ java -jar checkstyle-8.9-sevntu-1.29.0-all.jar -c TestConfig.xml TestClass.java
Starting audit...
[ERROR] TestClass.java:7: Condition with && at line 7 position 29 need optimization. All method calls are advised to move to end of logic expression. [LogicConditionNeedOptimization]
[ERROR] TestClass.java:8: Condition with && at line 8 position 41 need optimization. All method calls are advised to move to end of logic expression. [LogicConditionNeedOptimization]
Audit done.
Checkstyle ends with 2 errors.
````

Re-arranging any of the conditions will cause an NPE.

**Comment by rnveach** [comment]
> Please add it to UT

Done.

I have verified much of openjdk10 as it usually has interesting cases. I also checked the ones you didn't list and I didn't see anything new.

**Comment by romani** [comment]
> Assignments in conditions are bad practice anyways.

yes, could be done separately.

=============

ok to merge.

**Pull request merged**
