### PR TITLE
minor: define the new property in pom.xml and transfer it to ant run

### PR DESCRIPTION
**Pull request by mahfouz72**
part of https://github.com/checkstyle/checkstyle/pull/15376

### CODE REVIEW

**Comment by rnveach** [comment]
Eclipse and sonar failures can be ignored. They need their Java versions upgraded.

Have you done any checks to help ensure CS will pass with this merged?

**Comment by mahfouz72** [comment]
> Have you done any checks to help ensure your PR in CS will pass with this merged?

Nope. Is there a way to check this other than waiting for the merge and test?

**Comment by rnveach** [comment]
https://github.com/checkstyle/checkstyle/pull/15376#issuecomment-2267648774

The CI takes the PR's config and overlays it into this repo and runs it. That would be how you test it.

You would need to use your PR version of the config with the RedundantModifier change. That would require you to install the snapshot and use the snapshot version of CS in the run as well.

**Comment by mahfouz72** [comment]
@rnveach Yes. I mean I will be testing the upstream seventu that it will not be updated before the merge   
https://github.com/checkstyle/checkstyle/blob/d325ed0fb7ede71fe1327bc2bfef362d51bdaf99/.ci/validation.sh#L709
should I change this line to my fork?

**Comment by mahfouz72** [comment]
Test commit: https://github.com/checkstyle/checkstyle/pull/15376/commits/4baa2606b7e7d7a47dc253d9105b1c056ddeadc9
build URL: https://checkstyle.semaphoreci.com/workflows/4d7cd252-50aa-4653-b70d-3df56357de34?pipeline_id=f93bb76c-1cab-4317-9456-04accba9d232

no-error-seventu checks passed

**Review by rnveach — APPROVED** [review]

**Pull request merged**
