### PR TITLE
Issue #630: use checkstyle's utils instead of copying them

### PR DESCRIPTION
**Pull request by rnveach**
Issue #630 

Removed some duplicated utils from checkstyle.
Renaming of `CheckUtil` will have to wait until a new checkstyle release as there are some changes I need to make in checkstyle to make this util more globally acceptable.

### CODE REVIEW

**Comment by romani** [comment]
from Travis:
```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.116 sec <<< FAILURE! - in com.github.sevntu.checkstyle.internal.ChecksTest
verifyTestConfigurationFiles(com.github.sevntu.checkstyle.internal.ChecksTest)  Time elapsed: 0.109 sec  <<< FAILURE!
java.lang.AssertionError: no modules
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.github.sevntu.checkstyle.internal.ChecksTest.verifyTestConfigurationFiles(ChecksTest.java:61)
```

**Comment by rnveach** [comment]
Fixed.
I incorrectly assumed `ModuleReflectionsUtil` would scan all folders in the package. It doesn't.

**Comment by rnveach** [comment]
travis failure is weird issue with test referencing issue.

**Comment by rnveach** [comment]
CI is passing now.

**Pull request merged**
