### PR TITLE
Issue #918: fixes NPE from switch expression for PreferMethodReference

### PR DESCRIPTION
**Pull request by rnveach**
Issue #918

### CODE REVIEW

**Comment by rnveach** [comment]
Regression Report: http://rveach.no-ip.org:81/checkstyle/regression/315/

http://rveach.no-ip.org:81/checkstyle/regression/315/checkstyle/index.html#A2
There is a NPE with LogicConditionNeedOptimizationCheck on a Java 17 file.

There are no other non-antlr exceptions.

**Review by romani — APPROVED** [review]
Ok to merge

**Comment by romani** [comment]
Not sure why you used config with all Checks.

**Comment by rnveach** [comment]
To provide full regression and see if there was any other issues. It allowed me to find the NPE in the other issue/PR and prompted me to add checkstyle repo to our regression.

**Pull request merged**
