### PR TITLE
doc: Fix GH links to avoid 404 error

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Comment by rnveach** [comment]
wercker failure can be ignored, it shouldn't be running for gh-pages.

**Comment by rnveach** [comment]
@romani I am not seeing the error in our release notes template with missing `s`.
https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu_xdoc_freemarker.template#L12

It happened for latest release so it must still be an issue.

**Comment by romani** [comment]
I quickly made release notes manually, my bad

**Comment by romani** [comment]
@pzygielo , thanks a lot for fix

**Pull request merged**
