### PR TITLE
MapIterationInForEachLoopCheck + CustomDeclarationOrderCheck

### PR DESCRIPTION
**Pull request by damianszczepanik**
MapIterationInForEachLoopCheck 
- Converted strings to <type>.class.getName()
- moved initialization to beginTree method

CustomDeclarationOrderCheck
- Added tests to increase coverage
- Fixed rule in test method so more violations are raised
- Fixed formatting (indents)

### CODE REVIEW

**Comment by romani** [comment]
@damianszczepanik , please redo that PR.

**Comment by damianszczepanik** [comment]
Sorry for delay. I thought it was already merged.
Coverage decreases because I've added one method but I'm not sure if I rebased correctly...

**Comment by romani** [comment]
almost all outside PR are never appied without additonal changes :). 

@damianszczepanik , your branch (https://github.com/damianszczepanik/sevntu.checkstyle/commits/clearing-imports2) still consist changes that are not related to your issue, please fix.

Please create new branch and possibly new PR that will contain only meaningful changes that you are going to introduce. I recoomend you to split changes to each Check to separate PR to simplify acceptance process.

**Comment by damianszczepanik** [comment]
Sorry, for the problem. New PR is waiting for approval.

**Pull request closed without merging**
