### PR TITLE
Sonar violation: Tabulation characters should not be used

### PR DESCRIPTION
**Pull request by damianszczepanik**

### CODE REVIEW

**Comment by damianszczepanik** [comment]
I found classes that use only spaces, only tabs and both. I updated only those that have mix tab and spaces.

Sorry for double push - I forgot to add id of the PR into commit message.

**Comment by romani** [comment]
thanks a lot , I appreciate that !!!!!
double push is ok and does not bother me, final result is in priority.

We enforce checkstyle rules from main repo agaist this experimental project, #310 , as we have an idea to move all that Checks to main repo after testing period.

**Comment by damianszczepanik** [comment]
So do you want me to apply `.replaceAll("\y", "    ")` for all repo?

#310 sounds interesting, if you can provide some tips (I added comments) I will take it. Did you already update main checkstyle repo to validate against checkstyle? I couldn't find it in .travis configuration file.

**Comment by romani** [comment]
> Did you already update main checkstyle repo to validate against checkstyle?

yes, not all Checks are activated, but some of them.

>  I couldn't find it in .travis configuration file.

https://github.com/checkstyle/checkstyle/blob/master/.travis.yml#L8 in verify phase
https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L445

**Pull request merged**
