### PR TITLE
minor: adds sevntu compatibility matrix

### PR DESCRIPTION
**Pull request by rnveach**
I only wrote as far back as 1.30.0 but I can do all the way back.

Generated via:
````
@echo off

call :CheckSevntu 1.10.0
call :CheckSevntu 1.11.0
call :CheckSevntu 1.12.0
call :CheckSevntu 1.13.0
call :CheckSevntu 1.13.1
call :CheckSevntu 1.13.2
call :CheckSevntu 1.13.3
call :CheckSevntu 1.13.4
call :CheckSevntu 1.13.5
call :CheckSevntu 1.13.6
call :CheckSevntu 1.14.0
call :CheckSevntu 1.15.0
call :CheckSevntu 1.16.0
call :CheckSevntu 1.16.1
call :CheckSevntu 1.17.0
call :CheckSevntu 1.17.1
call :CheckSevntu 1.18.0
call :CheckSevntu 1.19.0
call :CheckSevntu 1.19.1
call :CheckSevntu 1.19.2
call :CheckSevntu 1.20.0
call :CheckSevntu 1.21.0
call :CheckSevntu 1.21.1
call :CheckSevntu 1.22.0
call :CheckSevntu 1.23.0
call :CheckSevntu 1.23.1
call :CheckSevntu 1.24.0
call :CheckSevntu 1.24.1
call :CheckSevntu 1.24.2
call :CheckSevntu 1.25.0
call :CheckSevntu 1.26.0
call :CheckSevntu 1.27.0
call :CheckSevntu 1.28.0
call :CheckSevntu 1.29.0
call :CheckSevntu 1.30.0
call :CheckSevntu 1.31.0
call :CheckSevntu 1.32.0
call :CheckSevntu 1.33.0
call :CheckSevntu 1.34.0
call :CheckSevntu 1.34.1
call :CheckSevntu 1.35.0
call :CheckSevntu 1.36.0
call :CheckSevntu 1.37.0
call :CheckSevntu 1.37.1
call :CheckSevntu 1.38.0
call :CheckSevntu 1.39.0
call :CheckSevntu 1.40.0
call :CheckSevntu 1.41.0
call :CheckSevntu 1.42.0
call :CheckSevntu 1.43.0

EXIT /B %ERRORLEVEL%

:CheckSevntu


echo Checking %~1

cd sevntu

git checkout %~1

cd sevntu-checks

echo cs eclipsecs expression
call mvn -e --no-transfer-progress -q -DforceStdout help:evaluate -D""expression=checkstyle.eclipse-cs.version""
echo.

echo checkstyle dependency
call mvn -e --no-transfer-progress dependency:tree | findstr checkstyle:jar
echo.

cd ..
cd ..

EXIT /B 0
````

Output:
````
Checking 1.10.0
cs eclipsecs expression
null object or invalid expression
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:5.6:compile

Checking 1.11.0
cs eclipsecs expression
null object or invalid expression
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:5.7:compile

Checking 1.12.0
cs eclipsecs expression
null object or invalid expression
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:5.7:compile

Checking 1.13.0
cs eclipsecs expression
null object or invalid expression
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:6.5:compile

Checking 1.13.1
cs eclipsecs expression
null object or invalid expression
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:6.5:compile

Checking 1.13.2
cs eclipsecs expression
null object or invalid expression
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:6.5:compile

Checking 1.13.3
cs eclipsecs expression
null object or invalid expression
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:6.5:compile

Checking 1.13.4
cs eclipsecs expression
null object or invalid expression
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:6.5:compile

Checking 1.13.5
cs eclipsecs expression
null object or invalid expression
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:6.5:compile

Checking 1.13.6
cs eclipsecs expression
null object or invalid expression
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:6.7:compile

Checking 1.14.0
cs eclipsecs expression
null object or invalid expression
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:6.7:compile

Checking 1.15.0
cs eclipsecs expression
null object or invalid expression
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:6.11.2:compile

Checking 1.16.0
cs eclipsecs expression
null object or invalid expression
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:6.11.2:compile

Checking 1.16.1
cs eclipsecs expression
null object or invalid expression
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:6.11.2:compile

Checking 1.17.0
cs eclipsecs expression
null object or invalid expression
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:6.11.2:compile

Checking 1.17.1
cs eclipsecs expression
null object or invalid expression
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:6.11.2:compile

Checking 1.18.0
cs eclipsecs expression
null object or invalid expression
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:6.11.2:compile

Checking 1.19.0
cs eclipsecs expression
6.16.1
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:6.16.1:compile

Checking 1.19.1
cs eclipsecs expression
6.16.1
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:6.16.1:compile

Checking 1.19.2
cs eclipsecs expression
6.16.1
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:6.16.1:compile

Checking 1.20.0
cs eclipsecs expression
6.16.1
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:6.16.1:compile

Checking 1.21.0
cs eclipsecs expression
6.16.1
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:6.16.1:compile

Checking 1.21.1
cs eclipsecs expression
6.16.1
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:6.16.1:compile

Checking 1.22.0
cs eclipsecs expression
7.2
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:7.2:compile

Checking 1.23.0
cs eclipsecs expression
7.2
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:7.2:compile

Checking 1.23.1
cs eclipsecs expression
7.2
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:7.2:compile

Checking 1.24.0
cs eclipsecs expression
7.2
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:7.2:compile

Checking 1.24.1
cs eclipsecs expression
7.6
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:7.6:compile

Checking 1.24.2
cs eclipsecs expression
7.6
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:7.6:compile

Checking 1.25.0
cs eclipsecs expression
7.6
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:7.6:compile

Checking 1.26.0
cs eclipsecs expression
8.5
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:8.5:compile

Checking 1.27.0
cs eclipsecs expression
8.7
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:8.7:compile

Checking 1.28.0
cs eclipsecs expression
8.8
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:8.8:compile

Checking 1.29.0
cs eclipsecs expression
8.9
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:8.9:compile

Checking 1.30.0
cs eclipsecs expression
8.10
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:8.10:compile

Checking 1.31.0
cs eclipsecs expression
8.11
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:8.11:compile

Checking 1.32.0
cs eclipsecs expression
8.12
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:8.12:compile

Checking 1.33.0
cs eclipsecs expression
8.18
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:8.18:compile

Checking 1.34.0
cs eclipsecs expression
8.18
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:8.18:compile

Checking 1.34.1
cs eclipsecs expression
8.18
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:8.18:compile

Checking 1.35.0
cs eclipsecs expression
8.18
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:8.18:provided

Checking 1.36.0
cs eclipsecs expression
8.26
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:8.26:provided

Checking 1.37.0
cs eclipsecs expression
8.26
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:8.26:provided

Checking 1.37.1
cs eclipsecs expression
8.29
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:8.29:provided

Checking 1.38.0
cs eclipsecs expression
8.29
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:8.29:provided

Checking 1.39.0
cs eclipsecs expression
8.29
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:8.29:provided

Checking 1.40.0
cs eclipsecs expression
8.40
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:8.40:provided

Checking 1.41.0
cs eclipsecs expression
9.1
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:9.1:provided

Checking 1.42.0
cs eclipsecs expression
10.0
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:10.0:provided

Checking 1.43.0
cs eclipsecs expression
10.4
checkstyle dependency
[INFO] +- com.puppycrawl.tools:checkstyle:jar:10.4:provided
````

### CODE REVIEW

**Comment by rnveach** [comment]
Display: https://github.com/rnveach/sevntu.checkstyle/tree/compatibility_matrix#compatibility-matrix

**Review by romani — APPROVED** [review]

**Comment by romani** [comment]
Travis was restarted

**Comment by rnveach** [comment]
New error looks stable but not related to my changes.
https://app.travis-ci.com/github/sevntu-checkstyle/sevntu.checkstyle/jobs/589571088#L383
> Caused by: java.lang.IllegalArgumentException: bundleLocation not found: /home/travis/.m2/repository/org/eclipse/orbit/bundles/org.apache.commons.io/2.6.0-SNAPSHOT/org.apache.commons.io-2.6.0-SNAPSHOT.jar

**Comment by rnveach** [comment]
@romani 
https://app.travis-ci.com/github/sevntu-checkstyle/sevntu.checkstyle/jobs/589571088#L366
> Eclipse-cs tag: 10.0.0

https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/eclipsecs-sevntu-plugin/pom.xml#L29
Shouldn't this say 10.4.0 since we are 10.4 ?

**Comment by romani** [comment]
We need to update to 10.4.0 of eclipsecs

**Comment by rnveach** [comment]
Rebased.

**Comment by rnveach** [comment]
CI passed. Nothing has changed, so I am merging.

**Pull request merged**
