### PR TITLE
Issue #425: New option to skip fields by regexp

### PR DESCRIPTION
**Pull request by cypai**
#425

### CODE REVIEW

**Comment by romani** [comment]
@cypai ,

1)
> logWarningIfAstDoesNotPass

if try to name method as "xxxxxxIfxxxxxxxxxx" that is big sign that smth is wrong in design.
Please inline this method to visitToken

2)
> 
```
 +        final boolean tokenIsField = isField(ast);
+        if (tokenIsField) {
+            if (!ignoreFieldNamePattern.matcher(getFieldName(ast)).find()) {
```

please move this code to `passCheck` method.

3)
>
` <regex><pattern>.*.checks.coding.NumericLiteralNeedsUnderscoreCheck</pattern><branchRate>95</branchRate><lineRate>93</lineRate></regex>`

please remove this line from pom.xml and make coverage 100%.

**Comment by cypai** [comment]
The only remaining non-covered lines are the default lines in the switch statements. Any suggestions?

**Comment by romani** [comment]
unfortunately, the only way to make it is to convert SWITCH to IF_ELSE and use reflection to get access to private methods.

Example:
code: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.java#L362
UT: https://github.com/checkstyle/checkstyle/blob/master/src/test/java/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheckTest.java#L420

but benefit of 100% coverage will be much better than such verbose and non-optimal structure and hacky UT.

**Comment by cypai** [comment]
What's the benefit for these last lines of coverage? I don't see any real benefits, plus this if-else structure is far less readable. It doesn't seem worth writing such hacky UTs that depend on internal implementation.

**Comment by romani** [comment]
> What's the benefit for these last lines of coverage?

the most valuable reason - absolutely no dead code. With coverage close to 100% there is possibility to introduce new code and miss coverage of it. I do not want to keep an eye on each code to be covered. That should be enforced by a coverage tool during build. Whole code in main checkstyle library is 100% covered. Benefit is enormous - I do not review coverage reports at all - they are 100% always. Any new code should be covered by UT.
 
Unfortunately coverage tools are not ideal and some design approaches are not so easy to mock Life is not ideal. We do hack (reflection) in UT area, so main code is not affected. Unfortunately your case is most problematic and to reach 100% we need to change main code. But slightly verbose code in comparison to threat to lose coverage is minor. 

After you got 100% coverage, nobody will be allowed to lower it. Code will be fully testable forever.

**Comment by romani** [comment]
@cypai , line from  sevntu-checks/pom.xml should be removed completely.

**Comment by cypai** [comment]
@romani Done.

**Comment by romani** [comment]
Usage of `@Test(expected=)` is highly discouraged it make test non-strict and just expect some Exception to happen .... please send separate PR with fix for this

**Comment by romani** [comment]
hmmm, https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/108 still not done ....... that is why it is not reported.

**Pull request merged**
