### PR TITLE
minor: sync eclipse-cs to 8.18

### PR DESCRIPTION
**Pull request by pzygielo**
https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/9765a3bf0f02272f921aec264667328f2ca60339/sevntu-checks/pom.xml#L19

### CODE REVIEW

**Comment by rnveach** [comment]
@romani please confrim I am not missing anything by updating these.

**Comment by pzygielo** [comment]
I was surprised why first commit built so successfully. But [Dependency Version Ranges](https://cwiki.apache.org/confluence/display/MAVENOLD/Dependency+Mediation+and+Conflict+Resolution#DependencyMediationandConflictResolution-DependencyVersionRanges) and [build](https://travis-ci.org/pzygielo/sevntu.checkstyle/jobs/564406175#L4918) confirmed (how could it not...) _soft_ requirement on `<version>8.12.0-SNAPSHOT</version>` (that was resolved to arifact 8.18.0-SNAPSHOT from local repository in that _green_,  case).

**Comment by rnveach** [comment]
@pzygielo While we are waiting on another review, please squash all commits to 1.

**Comment by pzygielo** [comment]
Perhaps unrelated, as I get it on master as well.

---
When I execute locally
```shell
.ci/travis.sh eclipse-cs
```
Unlike [on travis](https://travis-ci.org/sevntu-checkstyle/sevntu.checkstyle/jobs/564402039#L1158) following happens
```
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
[INFO] Computing target platform for MavenProject: com.github.sevntu-checkstyle:eclipsecs-sevntu-plugin:1.35.0 @ sevntu.checkstyle/eclipsecs-sevntu-plugin/pom.xml
[INFO] Resolving dependencies of MavenProject: com.github.sevntu-checkstyle:eclipsecs-sevntu-plugin:1.35.0 @ sevntu.checkstyle/eclipsecs-sevntu-plugin/pom.xml
[INFO] Cannot complete the request.  Generating details.
[INFO] Cannot complete the request.  Generating details.
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86_64}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: eclipsecs-sevntu-plugin 1.35.0
[ERROR]   Missing requirement: net.sf.eclipsecs.core 8.12.0.201907281241 requires 'package org.eclipse.core.filebuffers 0.0.0' but it could not be found
[ERROR]   Cannot satisfy dependency: eclipsecs-sevntu-plugin 1.35.0 depends on: bundle net.sf.eclipsecs.core 0.0.0
[ERROR] 
[ERROR] Internal error: java.lang.RuntimeException: No solution found because the problem
 is unsatisfiable.: [Unable to satisfy dependency from net.sf.eclipsecs.core 8.12.0.201907281241 to package org.eclipse.core.filebuffers 0.0.0.; Unable to satisfy dependency from net.sf.eclipsecs.core
 8.12.0.201907281241 to package org.eclipse.core.resources 0.0.0.; Unable to satisfy
 dependency from net.sf.eclipsecs.core 8.12.0.201907281241 to package
 org.eclipse.core.runtime 0.0.0.; Unable to satisfy dependency from net.sf.eclipsecs.core
 8.12.0.201907281241 to package org.eclipse.core.runtime.jobs 0.0.0.;
...
Unable to satisfy dependency from net.sf.eclipsecs.ui 8.12.0.201907281316 to package
 org.eclipse.ui.views.markers 0.0.0.; Unable to satisfy dependency from net.sf.eclipsecs.ui
 8.12.0.201907281316 to package org.osgi.framework 0.0.0.; Unable to satisfy dependency from
 net.sf.eclipsecs.ui 8.12.0.201907281316 to package org.osgi.service.prefs 0.0.0.; No solution
 found because the problem is unsatisfiable.]
```
openjdk version "1.8.0_212" + maven: 3.6.1 on linux

I unconfigured local maven mirror and built against empty local repository, but with no luck.

Before I digest [Tycho: Dependency Resolution Troubleshooting](https://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting) maybe you already know the solution?

**Comment by romani** [comment]
Strange that such version become unsync, they're referenced at "2.1) Recheck if that is required to update version of eclipse-cs " at https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/How-to-release-sevntu.checkstyle.

Update is correct.

**Pull request merged**
